apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-patch
  namespace: rustgrok
rules:
- apiGroups: ["networking.k8s.io"]
  resources: [ingresses]
  verbs: ["get","patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-patch
  namespace: rustgrok
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-patch
subjects:
- kind: ServiceAccount
  name: default
  namespace: rustgrok